### ISSUE TITLE
Referenced `yml` files are not copied

### ISSUE THREAD

**Issue by guoquan** [ikalnytskyi/sphinxcontrib-redoc#38]
My (local) yml spec file references to another (local) yml in the definition. However, the extension seems not able to detect the reference and copy them.
For example:

`a.yml`
```yaml
# ...
components:
  schemas:
    user:
      $ref: 'b.yml#/components/schemas/user'
# ...
``` 
`b.yml`
```yaml
# ...
components:
  schemas:
    user:
      type: object
# ...
```
and in `conf.py`
```python
# ...
redoc = [
    {
        "name": "My API",
        "page": "path/to/a",
        "spec": "path/to/a.yml",
    },
]
# ...
```
The extension detects `"path/to/a.yml"` and copy it to `_build/html/_spec`. However, `b.yml` is not copied and the page just failed to load.

Could there be a way to list the yml files I want to use for rendering the docs page, and the extension will copy and prepare them (and manipulate the paths) for me?
